### ISSUE TITLE
building a debug version of llvm

### ISSUE THREAD

**Issue by abduld** [termoshtt/llvmenv#11]
is there a way to specify that I need a debug version of llvm to be installed?

thanks

**Comment by termoshtt** [comment]
There is `build` option in `entry.toml`:

```toml
[llvm-dev]
llvm_git = "https://github.com/llvm-mirror/llvm"
clang_git = "https://github.com/llvm-mirror/clang"
target   = ["X86"]
build = "Debug"   # will be -DCMAKE_BUILD_TYPE=Debug
example  = 0
document = 0
```

This option should be generated by `llvmenv init` sample. I will fix it, thanks
