### ISSUE TITLE
Whitelist for install executables

### ISSUE THREAD

**Issue by termoshtt** [termoshtt/llvmenv#15]
Only a few executables are necessary to be built in most cases. We need an option for it:

```toml
[llvm-dev]
llvm_git  = "https://github.com/llvm-mirror/llvm"
clang_git = "https://github.com/llvm-mirror/clang"
target    = ["X86"]
build     = "Release"
executable = ["clang", "llvm-mc", "opt"]   # like this!
```
